### ISSUE TITLE
Hyperclient::Resource#to_h != Hyperclient::Resource#to_hash

### ISSUE THREAD

**Issue by jufemaiz** [codegram/hyperclient#103]
Hi guys, I'm using v0.8.1 and am having a discrepancy when using #to_h in place of #to_hash on a Hyperclient::Resource.

```ruby
cluster_meters = Source.clusters._get.by_id(id: id)._get.meters._embedded
meter = gateway_meters.all.first
expect(meter.to_h).to eq(meter.to_hash)
```

However the call to #to_h returns nil, while the call to #to_hash returns the expected hash

**Comment by dblock** [comment]
Interesting, probably just a bug.

**Comment by jufemaiz** [comment]
Ok, a bit of poking and I've discovered it.

Array#to_h exists
Array#to_hash doesn't exist

https://github.com/codegram/hyperclient/blob/39a07cb17dd0a16c818f3f2cc58f195a7186545e/lib/hyperclient/resource.rb#L87

Given that Hyperclient::Resource#to_hash has no arguments passed, we don't actually get to do anything with the to_h method on the Hyperclient::Resource, and there's nothing returned, hence "nil" is the result.

Dumb question, why is the !Array.method_defined?(method) used there?

**Comment by dblock** [comment]
Honestly I don't remember the reason for that `Array.defined`, `git blame` should surface it. There was definitely a test for this that was failing at some point.

**Comment by jufemaiz** [comment]
[https://github.com/codegram/hyperclient/commit/03ecf0ad458437220f77cfcb0116916a52c8add1](https://github.com/codegram/hyperclient/commit/03ecf0ad458437220f77cfcb0116916a52c8add1)

But before that it was an Enumerable check.

https://github.com/codegram/hyperclient/commit/13a62b3e5e4d78da08c7816a127aab6c841fd66f

**Comment by dblock** [comment]
Are you running `rake` with all the tests? I think you're missing the feature scenarios. That commit has a test with `each` that otherwise fails.

**Comment by jufemaiz** [comment]
rake spinache output:

```
Feature: API navigation

  Scenario: Links
    !  When I connect to the API                                   # features/support/api.rb:19
    ~  Then I should be able to navigate to posts and authors

        getaddrinfo: nodename nor servname provided, or not known
        /Users/joelcourtney/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/net/http.rb:879:in `initialize'

  Scenario: Templated links
    !  Given I connect to the API                                       # features/support/api.rb:19
    ~  When I search for a post with a templated link
    ~  Then the API should receive the request with all the params

        getaddrinfo: nodename nor servname provided, or not known
        /Users/joelcourtney/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/net/http.rb:879:in `initialize'

  Scenario: Attributes
    !  Given I connect to the API                               # features/support/api.rb:19
    ~  When I load a single post
    ~  Then I should be able to access it's title and body

        getaddrinfo: nodename nor servname provided, or not known
        /Users/joelcourtney/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/net/http.rb:879:in `initialize'

  Scenario: Embedded resources
    !  Given I connect to the API                                       # features/support/api.rb:19
    ~  When I load a single post
    ~  Then I should also be able to access it's embedded comments

        getaddrinfo: nodename nor servname provided, or not known
        /Users/joelcourtney/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/net/http.rb:879:in `initialize'

  Scenario: Navigation links
    !  When I connect to the API                                         # features/support/api.rb:19
    ~  Then I should be able to navigate to next page
    ~  Then I should be able to navigate to next page without links

        getaddrinfo: nodename nor servname provided, or not known
        /Users/joelcourtney/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/net/http.rb:879:in `initialize'

  Scenario: Counts
    !  When I connect to the API                                 # features/support/api.rb:19
    ~  Then I should be able to count embedded items
    ~  Then I should be able to iterate over embedded items

        getaddrinfo: nodename nor servname provided, or not known
        /Users/joelcourtney/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
```

This continues all the way through.

**Comment by mosboomu** [comment]
lib/uri_template/rfc6570/expression.rb

**Comment by jufemaiz** [comment]
@dblock 🎉
