### ISSUE TITLE
Broken specs on Ruby 2.6.3

### ISSUE THREAD

**Issue by ivoanjo** [codegram/hyperclient#137]
Just noticed that there's a couple of broken specs on Ruby 2.6. Haven't had a chance to look into them:

```
Hyperclient::LinkCollection
     FAIL (0:00:00.083) test_0003_returns link objects for each link
          Expected #<Enumerator: #<Hyperclient::LinkCollection:0x0000561e2f7ff8e8 @_curies={"image"=>#<Hyperclient::Curie {"name"=>"image", "href"=>"/docs/images/{rel}", "templated"=>true}>}, @collection={"self"=>#<Hyperclient::Link(self) {"href"=>"/productions/1"}>, "filter"=>#<Hyperclient::Link(filter) {"href"=>"/productions/1?categories={filter}", "templated"=>true}>, "gizmos"=>[#<Hyperclient::Link(gizmos) {"href"=>"/gizmos/1"}>, #<Hyperclient::Link(gizmos) {"href"=>"/gizmos/2"}>], "curies"=>[#<Hyperclient::Link(curies) {"name"=>"image", "href"=>"/docs/images/{rel}", "templated"=>true}>], "null_link"=>nil, "image:thumbnail"=>#<Hyperclient::Link(image:thumbnail) {"href"=>"/images/thumbnails/{version}.jpg", "templated"=>true}>}>:filter> to be a kind of Hyperclient::Link, not Enumerator.
        @ (eval):8:in `must_be_kind_of'
          test/hyperclient/link_collection_test.rb:26:in `block (2 levels) in <module:Hyperclient>'

```

```
Hyperclient::LinkCollection::templated link
    ERROR (0:00:00.090) test_0001_must expand
          undefined method `_expand' for #<Enumerator:0x0000561e2f836f28>
        @ test/hyperclient/link_collection_test.rb:43:in `block (3 levels) in <module:Hyperclient>
```

**Comment by dblock** [comment]
I believe this was fixed in #145, works for me on 2.6.3 now.
